### ISSUE TITLE
Plese Add gamedb fixed into build and FPS control hack

### ISSUE THREAD

**Issue by Riot20058** [Trixarian/NetherSX2-classic#1]
See this not update long time wonder move so hack for Netersx2 Patch to Netersx2 Classic like able used in order run it most game work batter on 3668 like Urban Reign and sly cooper games. Or reason why not be added at all

**Comment by Riot20058** [comment]
@Trixarian never going update this ver most games work batter on this build they 4248 and like used gamedb patch and Fps control hack itself don't understand why 4248 so used way whost come fps.

**Comment by Trixarian** [comment]
I am planning to update this when I release 1.9 of NetherSX2-patch, including porting over features back to Classic. Learn some patience. Also if you ever drag your crappy opinion of me into someone else's issue again, I will block you
